module: MaterialComponentsFontDiskLoader
module_version: 1.0.0
umbrella_header: src/MaterialComponentsFontDiskLoader.h
objc: true
sdk: iphonesimulator
github_url: https://github.com/material-foundation/material-font-disk-loader-ios
github_file_prefix: https://github.com/material-foundation/material-font-disk-loader-ios/tree/v1.0.0
